import { Y } from "./Y";

export interface Squarespace {
  AFTER_BODY_LOADED: boolean;
  INITIALIZED: boolean;
  SQUARESPACE_INITIALIZED_ONCE: boolean;
  addLoadTrigger: () => void;
  afterBodyLoad: () => void;
  createCookie: () => void;
  getSession: () => void;
  globalDestroy: () => void;
  globalInit: () => void;
  globalMarkReady: () => void;
  initializeAccordionBlock: () => void;
  initializeAcuityBlocks: () => void;
  initializeAspectRatioBlocks: () => void;
  initializeButtonBlock: () => void;
  initializeCartPage: () => void;
  initializeChartBlock: () => void;
  initializeCollectionPages: () => void;
  initializeCommerce: () => void;
  initializeDisqusCommentLinks: () => void;
  initializeDonationButton: () => void;
  initializeFormBlocks: () => void;
  initializeGlobalLightbox: () => void;
  initializeImageBlockDynamicElements: () => void;
  initializeLayoutBlocks: () => void;
  initializeMarqueeBlock: () => void;
  initializeMemberAreaBlock: () => void;
  initializeMenuBlock: () => void;
  initializeNativeVideo: () => void;
  initializeNewsletterBlock: () => void;
  initializeOpenTableBlock: () => void;
  initializeOpenTableV2Block: () => void;
  initializePageContent: () => void;
  initializeScaledText: () => void;
  initializeSearchBlock: () => void;
  initializeSocialLinks: () => void;
  initializeSoundcloudBlock: () => void;
  initializeSummaryV2Block: () => void;
  initializeSvgs: () => void;
  initializeVideo: () => void;
  initializeVideoBlock: () => void;
  initializeZolaBlocks: () => void;
  injectRollups: () => void;
  load: () => void;
  onDestroy: () => void;
  onInitialize: (a: Y, b: () => void) => void;
  setSession: () => void;
  shouldRedirectToConfig: () => void;
  _humanizeAllDates: () => void;
  _injectStylesheetFromTopFrame: () => void;
  _resizeEmitter: object;
  _userHasViewerRole: () => void;
  _yuiaop: object;
  _yuid: string;
}
